/*
DROP TABLE IF EXISTS `APPLICATIONS`;
DROP TABLE IF EXISTS `TECHNOLOGIES`;
DROP TABLE IF EXISTS `APPLICANTS`;
DROP TABLE IF EXISTS `APPLICANTS_TECHNOLOGIES`;
*/

CREATE TABLE `APPLICATIONS` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `APPLICANT_ID` INTEGER NOT NULL,
    `UNIX_TIMESTAMP` BIGINT NOT NULL DEFAULT 0,
    `SIGNATURE` VARCHAR(255) NOT NULL DEFAULT '0',
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_APPLICATION_2_APPLICANT` FOREIGN KEY (`APPLICANT_ID`) REFERENCES APPLICANTS(`ID`) ON DELETE CASCADE
);

CREATE TABLE `TECHNOLOGIES` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `APPLICANTS` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `FIRST_NAME` VARCHAR(255) NOT NULL,
    `LAST_NAME` VARCHAR(255) NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL,
    `BIO` TEXT NOT NULL,
    `VCS_URL` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `APPLICANTS_TECHNOLOGIES` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `APPLICANT_ID` INTEGER NOT NULL,
    `TECHNOLOGY_ID` INTEGER NOT NULL,
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_AT_2_APPLICANT` FOREIGN KEY (`APPLICANT_ID`) REFERENCES APPLICANTS(`ID`) ON DELETE CASCADE,
    CONSTRAINT `FK_AT_2_TECHNOLOGY` FOREIGN KEY (`TECHNOLOGY_ID`) REFERENCES TECHNOLOGIES(`ID`) ON DELETE CASCADE
);

/*The use of a differnet delimiter is required in MySQL if a trigger or procedure contains multiple statements*/
DELIMITER //

CREATE TRIGGER `SIGNATURE_CALC` BEFORE
    INSERT ON `APPLICATIONS` FOR EACH ROW
BEGIN
    IF NEW.`UNIX_TIMESTAMP` IS NULL THEN
        SET NEW.`UNIX_TIMESTAMP` = CURRENT_TIMESTAMP;
    END IF;

    IF NEW.`SIGNATURE` IS NULL THEN
        SET NEW.`SIGNATURE` = SHA1(CONCAT(NEW.`UNIX_TIMESTAMP`, 'credy'));
    END IF;
END;

// 

DELIMITER;